# Generated by Django 3.2.19 on 2023-06-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='xml_sps',
        ),
    ]
